# Generated by Django 4.0.4 on 2022-05-09 15:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_rename_is_serviceprovider_customuser_is_loanprovider_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='loanrequestspost',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9999999), django.core.validators.MinValueValidator(0)])),
                ('accept', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
