# Generated by Django 4.0.4 on 2022-05-09 15:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrequestspost',
            name='amount',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9999999), django.core.validators.MinValueValidator(0)]),
        ),
    ]
