# Generated by Django 4.0.4 on 2022-05-09 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanapp', '0002_alter_loanrequestspost_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrequestspost',
            name='accept',
            field=models.BooleanField(default=False),
        ),
    ]
