# Generated by Django 4.0.4 on 2022-05-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanapp', '0003_alter_loanrequestspost_accept'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanrequestspost',
            name='accept',
        ),
        migrations.AddField(
            model_name='loanrequestspost',
            name='time_added',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
