# Generated by Django 4.0.4 on 2022-05-09 16:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanapp', '0004_remove_loanrequestspost_accept_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrequestspost',
            name='intrest',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(3)]),
        ),
        migrations.AddField(
            model_name='loanrequestspost',
            name='months',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(60), django.core.validators.MinValueValidator(1)]),
        ),
    ]
