# Generated by Django 4.0.4 on 2022-05-10 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanapp', '0005_loanrequestspost_intrest_loanrequestspost_months'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loanrequestspost',
            options={'ordering': ['amount']},
        ),
        migrations.AddField(
            model_name='loanrequestspost',
            name='accepted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='loanrequestspost',
            name='accepter_msg',
            field=models.TextField(blank=True, null=True),
        ),
    ]
