# Generated by Django 4.0.4 on 2022-05-08 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_rename_is_serviceprovider_customuser_is_loanprovider_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='profilemodel',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('time_added', models.DateTimeField(auto_now_add=True)),
                ('selfie', models.ImageField(upload_to='images/userprofile/selfie')),
                ('CTC', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('Bank_Name', models.CharField(max_length=40)),
                ('Account_Number', models.CharField(max_length=16)),
                ('Aadhar_Card', models.ImageField(upload_to='images/userprofile/adharcard')),
                ('Pan_Card', models.ImageField(upload_to='images/userprofile/pancard')),
                ('Pancard_Number', models.CharField(max_length=10)),
                ('Salary_clip', models.FileField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Salary_clips', models.FileField(upload_to='images/userprofile/salaryclips')),
                ('profile', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='userdetails.profilemodel')),
            ],
        ),
    ]
