# Generated by Django 4.0.4 on 2022-05-08 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0003_alter_profilemodel_salary_clip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='Aadhar_Card',
            field=models.ImageField(blank=True, upload_to='images/userprofile/adharcard'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='Account_Number',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='Bank_Name',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='CTC',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='Pan_Card',
            field=models.ImageField(blank=True, upload_to='images/userprofile/pancard'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='Pancard_Number',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='Salary_clip',
            field=models.FileField(blank=True, upload_to='images/userprofile/salarslips'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='first_name',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='last_name',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='selfie',
            field=models.ImageField(blank=True, upload_to='images/userprofile/selfie'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='time_added',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
