# Generated by Django 4.0.4 on 2022-05-09 10:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0008_alter_profilemodel_aadhar_card_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='age',
            field=models.IntegerField(default=18, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(18)]),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='cibil_score',
            field=models.IntegerField(default=300, validators=[django.core.validators.MaxValueValidator(700), django.core.validators.MinValueValidator(300)]),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='repayment_score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='years_of_work_experience',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(40), django.core.validators.MinValueValidator(1)]),
        ),
    ]
