# Generated by Django 4.1.5 on 2023-04-24 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0009_profilemodel_age_profilemodel_cibil_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='CTC',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
