# Generated by Django 4.1.5 on 2023-04-24 10:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0010_alter_profilemodel_ctc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='cibil_score',
            field=models.IntegerField(default=500, validators=[django.core.validators.MaxValueValidator(700), django.core.validators.MinValueValidator(500)]),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='years_of_work_experience',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(40), django.core.validators.MinValueValidator(0)]),
        ),
    ]
