# Generated by Django 4.0.4 on 2022-05-08 07:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_serviceProvider',
            new_name='is_loanProvider',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_serviceBusiness',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
        migrations.AlterField(
            model_name='fundraiser',
            name='image',
            field=models.ImageField(default=' ', upload_to='dynamic/img/user_image', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg'])]),
        ),
        migrations.DeleteModel(
            name='userprofile',
        ),
    ]
